SET IDENTITY_INSERT COMUM.TB_PRODUTO  ON
INSERT INTO COMUM.TB_PRODUTO (PR_ID,PR_NOME,PR_DESCRICAO,PR_TITULO_IMG,PR_IMG_PRINCIPAL,PR_CSS_DEFAULT,PL_ID) VALUES (311,'projeto','Projeto','','','default',1);
SET IDENTITY_INSERT COMUM.TB_PRODUTO  OFF

INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginTipo','INTERNO_EXTERNO',311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginAreaInterno','Área do Servidor',311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginChaveAcessoInterno','Usuário do Compras',311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginFacebookInterno','false',311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginEsqueceuSenhaInterno','true',311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginAutoCadastroInterno','false',311);

INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginAreaExterno','Área do Fornecedor',311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginChaveAcessoExterno','CPF ou Email',311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginFacebookExterno','false',311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginEsqueceuSenhaExterno','true',311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginAutoCadastroExterno','true',311);

INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PA_TIPO, PR_ID) VALUES ('logo', 'repo1:projeto/logo.svg', 'ARQUIVO', 311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PA_TIPO, PR_ID) VALUES ('logoEmail', 'repo1:projeto/logoEmail.png', 'ARQUIVO', 311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PA_TIPO, PR_ID) VALUES ('logoMenu', 'repo1:projeto/logoMenu.svg', 'ARQUIVO', 311);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PA_TIPO, PR_ID) VALUES ('logoMenuRetraido', 'repo1:projeto/logoMenuRetraido.svg', 'ARQUIVO', 311);