create schema projeto;

-- Sequences
CREATE SEQUENCE PROJETO.SEQ_PROJETO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCACHE;

--Tables
--Comments

CREATE TABLE PROJETO.TB_PROJETO (
    PR_ID NUMBER(10) PRIMARY KEY,
    PR_NOME VARCHAR2(100),
    PR_DESCRICAO VARCHAR2(500),
    PR_DTHR_INICIAL TIMESTAMP(6),
    PR_DTHR_FINAL TIMESTAMP(6),
    PR_SITUACAO VARCHAR2(20),
    PR_CATEGORIA VARCHAR2(20),
    PR_URI_LOGO VARCHAR2(100),
    PR_DTHR_CADASTRO TIMESTAMP(6),
    PR_DTHR_ALTERACAO TIMESTAMP(6),
    PR_USUARIO_CADASTRO VARCHAR2(255),
    PR_USUARIO_ALTERACAO VARCHAR2(255)
);

COMMENT ON TABLE PROJETO.TB_PROJETO IS 'Tabela onde são registradas os clientes.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_ID IS 'Chave primária da tabela.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_NOME IS 'Nome do projeto.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_DESCRICAO IS 'Descrição do projeto.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_DTHR_INICIAL IS 'Data/Hora inicial do projeto.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_DTHR_FINAL IS 'Data/Hora final do projeto.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_SITUACAO IS 'Situação do projeto.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_CATEGORIA IS 'Categoria do projeto.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_URI_LOGO IS 'Uri da logo do projeto.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_DTHR_CADASTRO IS 'Data/Hora de criação do registro.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_DTHR_ALTERACAO IS 'Data/Hora da última alteração do registro.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_USUARIO_CADASTRO IS 'Usuário que criou o registro.';
COMMENT ON COLUMN PROJETO.TB_PROJETO.PR_USUARIO_ALTERACAO IS 'Último usuário a alterar o registro.';

-- Indexes

CREATE INDEX IDX_PR_PR_NOME ON PROJETO.TB_PROJETO (PR_NOME);
